# Generated by Django 3.2.7 on 2025-12-23 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indoor_object_detection', '0002_fileupload_created_at'),
    ]

    operations = [
    ]
